#!/usr/bin/env python3
"""Generate a synthetic paper and run the patent-disclosure toolchain end to end."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
ROOT = SKILL_DIR.parents[2]
DEFAULT_WORKDIR = Path("/tmp/patent_disclosure_e2e")

for _p in [Path.home() / ".npm-global" / "bin", Path.home() / ".local" / "bin"]:
    if _p.is_dir():
        os.environ["PATH"] = str(_p) + os.pathsep + os.environ.get("PATH", "")


def run(cmd: list[str], *, cwd: Path | None = None, stdout: Path | None = None) -> subprocess.CompletedProcess:
    print("[run]", " ".join(cmd), file=sys.stderr)
    kwargs = {
        "cwd": str(cwd) if cwd else None,
        "text": True,
        "capture_output": stdout is None,
        "timeout": 180,
    }
    if stdout is not None:
        with stdout.open("w", encoding="utf-8") as f:
            r = subprocess.run(cmd, stdout=f, stderr=subprocess.PIPE, text=True, cwd=str(cwd) if cwd else None, timeout=180)
    else:
        r = subprocess.run(cmd, **kwargs)
    if r.returncode != 0:
        if stdout is None:
            print(r.stdout, file=sys.stderr)
            print(r.stderr, file=sys.stderr)
        else:
            print(r.stderr, file=sys.stderr)
        raise RuntimeError(f"command failed: {' '.join(cmd)}")
    return r


def write_synthetic_latex(workdir: Path) -> Path:
    paper_dir = workdir / "synthetic_paper"
    paper_dir.mkdir(parents=True, exist_ok=True)
    (paper_dir / "main.tex").write_text(textwrap.dedent(r"""
        \documentclass{article}
        \title{Adaptive Mask-Guided Feature Fusion for Robust Medical Image Segmentation}
        \begin{document}
        \maketitle
        \begin{abstract}
        We propose an adaptive mask-guided feature fusion framework for robust medical image segmentation.
        The framework combines multi-scale feature extraction, uncertainty gating, and boundary-aware refinement.
        It improves Dice by 2.7 percentage points and reduces inference latency by 18\% on a representative benchmark.
        \end{abstract}
        \keywords{medical image segmentation, feature fusion, uncertainty gate, boundary refinement}

        \section{Introduction}
        Existing segmentation systems usually fuse multi-scale features with fixed weights. Such systems are sensitive
        to noisy boundaries and small lesion regions. The contributions are:
        \begin{itemize}
        \item We design a mask-guided feature fusion module that selects reliable local and global features.
        \item We introduce an uncertainty gate to suppress noisy boundary responses before decoding.
        \item We add a boundary-aware refinement head that improves small target segmentation with low overhead.
        \end{itemize}

        \section{Related Work}
        A common method extracts encoder features at multiple scales and concatenates them before a decoder.
        Another method uses attention maps to weight features, but the attention maps are not constrained by lesion masks.

        \section{Method}
        Given an input image $X \in \mathbb{R}^{H \times W \times C}$, an encoder generates features
        $F_1, F_2, F_3$. A mask prior $M$ is generated by a lightweight prediction branch. The fusion gate is computed by
        \begin{equation}
        G = \sigma(W_g [F_i, M, U] + b_g)
        \end{equation}
        where $U$ denotes uncertainty estimated from feature variance. The fused feature is
        \begin{equation}
        Z_i = G \odot F_i + (1-G) \odot R_i
        \end{equation}
        where $R_i$ is a residual feature from the adjacent scale.

        \begin{figure}
        \caption{Overall architecture of the adaptive mask-guided fusion framework.}
        \end{figure}

        \section{Experiments}
        On the SynMed benchmark, the method improves Dice from 86.4\% to 89.1\%, reduces Hausdorff distance by 11.3\%,
        and reduces latency from 42 ms to 34 ms on an NVIDIA A100 GPU.

        \section{Conclusion}
        The proposed framework improves segmentation robustness and efficiency through mask-guided fusion,
        uncertainty gating, and boundary-aware refinement.
        \end{document}
    """).strip() + "\n", encoding="utf-8")
    return paper_dir


def build_disclosure(parsed: dict, patents: list[dict], outdir: Path) -> Path:
    title = parsed.get("title", "Adaptive Mask-Guided Feature Fusion")
    patent_lines = []
    for p in patents[:3]:
        if p.get("source") == "no_results":
            continue
        patent_lines.append(f"- {p.get('patent_no', '')}：{p.get('title', '')}，申请人：{p.get('applicant', '')}")
    if not patent_lines:
        patent_lines.append("- 未检索到直接相关专利，背景技术基于论文 Related Work 归纳。")

    md = f"""# 一种掩码引导特征融合的图像分割方法

## 技术领域

本发明涉及人工智能和医学图像处理技术领域，更具体地，涉及图像语义分割中的多尺度特征融合、边界细化和不确定性抑制方法。

## 背景技术

图像分割是医学影像辅助诊断、病灶定位和定量分析中的关键技术。近年来，基于深度学习的编码器-解码器网络已广泛用于器官、病灶和血管区域的自动分割。

在现有技术中，针对多尺度图像分割问题，通常先通过卷积神经网络或变换器编码器提取不同尺度的特征图，再将各尺度特征进行拼接、相加或注意力加权，最后输入解码器生成分割掩码。部分现有方案进一步通过边界分支或注意力图增强目标区域响应。

然而，上述现有技术仍存在以下技术问题：（1）多尺度特征融合权重固定或缺少可靠掩码约束，导致小目标和低对比区域容易被背景噪声淹没；（2）边界附近的不确定响应未被显式抑制，导致分割边缘断裂或外溢；（3）单纯增加注意力或边界分支会提高计算开销，难以兼顾实时推理需求。

## 发明内容

本发明提出一种掩码引导特征融合的图像分割方法，通过目标区域掩码先验和不确定性图约束多尺度特征融合过程，根据医学图像中目标区域边界模糊、小目标占比低以及背景噪声强的特征，构造门控融合和边界细化联合处理流程，从而提高图像分割结果的准确性和稳定性。本方法适用于医学图像、工业缺陷图像以及其他具有小目标和模糊边界的图像分割场景。

本发明是通过以下技术方案实现的：

本发明涉及一种掩码引导特征融合的图像分割方法，通过读取待分割图像并提取多尺度特征，从多尺度特征中生成目标区域掩码先验和不确定性图，再利用门控融合模块得到融合特征，最终通过边界细化模块和解码器输出分割掩码。

所述的待分割图像是指输入至分割系统的二维或三维图像数据，其尺寸表示为 $X \\in \\mathbb{{R}}^{{H \\times W \\times C}}$。所述的多尺度特征是指由编码器在不同下采样倍率下输出的特征图 $F_1,F_2,F_3$。

所述的目标区域掩码先验是指由轻量预测分支根据多尺度特征生成的候选目标区域概率图，用于约束后续特征融合过程。所述的不确定性图是指根据相邻尺度特征方差或预测分布差异计算得到的边界不可靠区域响应图。

所述的门控融合模块是指：针对第 $i$ 个尺度的特征图，将该尺度特征 $F_i$、目标区域掩码先验 $M$ 以及不确定性图 $U$ 进行拼接，利用可学习参数 $W_g$ 和 $b_g$ 计算融合门控 $G$，其计算方式为：

$$
G = \\sigma(W_g [F_i, M, U] + b_g)
$$

所述的特征融合是指：根据融合门控 $G$ 对当前尺度特征 $F_i$ 和相邻尺度残差特征 $R_i$ 进行加权组合，得到融合特征 $Z_i$，其计算方式为：

$$
Z_i = G \\odot F_i + (1-G) \\odot R_i
$$

所述的边界细化模块是指：利用融合特征 $Z_i$ 预测目标边界响应，并将该边界响应反馈至解码器，使解码器在输出分割掩码时增强目标边缘区域的连续性。

本发明涉及一种实现上述图像分割方法的系统，包括：图像读取模块、图像预处理模块、多尺度特征提取模块、掩码先验生成模块、不确定性估计模块、门控融合模块、边界细化模块和分割输出模块，其中：图像读取模块载入待分割图像并将图像输出至图像预处理模块；图像预处理模块对图像进行归一化和尺度变换并输出至多尺度特征提取模块；多尺度特征提取模块输出多尺度特征至掩码先验生成模块、不确定性估计模块和门控融合模块；门控融合模块根据掩码先验和不确定性图生成融合特征；边界细化模块根据融合特征生成边界响应；分割输出模块结合融合特征和边界响应得到最终分割掩码。

## 技术效果

相比现有技术在模糊边界和小目标场景下分割结果容易断裂或外溢的问题，本发明通过掩码先验约束多尺度融合过程，降低背景噪声对小目标分割的影响；通过不确定性门控抑制边界附近不可靠响应，提高边界连续性。在合成测试论文给出的实验设置中，Dice 指标由86.4\\%提升至89.1\\%，推理延迟由42ms降低至34ms。本方法不仅限于医学图像分割，也可适用于工业缺陷检测、遥感目标提取等具有类似目标边界特征的图像分割任务。

## 附图说明

图 1 为本发明实施例的系统整体架构示意图；
图 2 为本发明实施例的掩码引导特征融合方法流程示意图；

## 具体实施方式

本实施例通过实施上述图像分割系统，使用掩码引导特征融合方法对医学图像中的目标区域进行分割。将待分割医学图像存储在计算机中，利用本发明的系统对该图像进行分析。

如图1所示，本实施例的系统包括图像读取模块、图像预处理模块、多尺度特征提取模块、掩码先验生成模块、不确定性估计模块、门控融合模块、边界细化模块和分割输出模块。

```mermaid
flowchart TB
    A[输入图像] --> B[图像预处理模块]
    B --> C[多尺度特征提取模块]
    C --> D[掩码先验生成模块]
    C --> E[不确定性估计模块]
    C --> F[门控融合模块]
    D --> F
    E --> F
    F --> G[边界细化模块]
    G --> H[分割输出模块]
```

如图2所示，本实施例具体包括以下步骤：

①读取待分割图像作为初始图像 $X$，对其进行归一化和尺度变换，得到预处理图像；

②将预处理图像输出至多尺度特征提取模块，得到特征图 $F_1,F_2,F_3$；

③掩码先验生成模块根据多尺度特征生成目标区域掩码先验 $M$，不确定性估计模块根据多尺度特征差异生成不确定性图 $U$；

④门控融合模块根据 $F_i$、$M$ 和 $U$ 计算融合门控 $G$，并生成融合特征 $Z_i$；

⑤边界细化模块根据融合特征生成边界响应，分割输出模块结合融合特征和边界响应生成分割掩码；

⑥输出最终分割结果。

```mermaid
flowchart LR
    S1[获取输入图像] --> S2[提取多尺度特征]
    S2 --> S3[生成掩码先验]
    S2 --> S4[估计不确定性]
    S3 --> S5[计算融合门控]
    S4 --> S5
    S5 --> S6[融合相邻尺度特征]
    S6 --> S7[边界细化]
    S7 --> S8[输出分割掩码]
```

在一个医学图像分割实施例中，输入图像大小为 $512 \\times 512$，编码器输出三个尺度特征图，门控融合模块对每一尺度独立计算 $G$。实验结果显示，本发明方法Dice达到89.1\\%，Hausdorff距离降低11.3\\%，推理延迟降低18\\%。整个系统中的各个模块均为本发明的核心内容，各模块的输出结果相互关联，应按照上述步骤执行。

上述具体实施可由本领域技术人员在不背离本发明原理和宗旨的前提下以不同方式进行局部调整，本发明的保护范围以权利要求书为准且不由上述具体实施所限。

## 权利要求要点（供代理人参考）

1. 方法权利要求：围绕多尺度特征、掩码先验、不确定性图和门控融合公式进行限定。
2. 装置权利要求：围绕预处理、特征提取、掩码生成、不确定性估计、门控融合、边界细化和输出模块进行限定。
3. 存储介质权利要求：计算机程序被处理器执行时实现上述方法步骤。

## 参考专利（供代理人参考）

{chr(10).join(patent_lines)}
"""
    outdir.mkdir(parents=True, exist_ok=True)
    path = outdir / "20260602_自适应融合_patent_disclosure.md"
    path.write_text(md, encoding="utf-8")
    return path


def assert_outputs(outdir: Path, md_path: Path, docx_path: Path) -> None:
    if not md_path.is_file():
        raise AssertionError(f"missing markdown: {md_path}")
    if not docx_path.is_file() or docx_path.stat().st_size < 1000:
        raise AssertionError(f"missing or tiny docx: {docx_path}")
    pngs = sorted(outdir.glob("fig_*.png"))
    if len(pngs) < 2:
        raise AssertionError("expected at least two generated PNG figures")
    text = md_path.read_text(encoding="utf-8")
    forbidden = ["本文", "我们", "作者", "新颖的", "先进的"]
    bad = [w for w in forbidden if w in text]
    if bad:
        raise AssertionError(f"forbidden words found: {bad}")
    for heading in ["技术领域", "背景技术", "发明内容", "技术效果", "附图说明", "具体实施方式"]:
        if heading not in text:
            raise AssertionError(f"missing heading: {heading}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Run patent-disclosure end-to-end test")
    ap.add_argument("--workdir", default=str(DEFAULT_WORKDIR), help="test working directory")
    ap.add_argument("--keep", action="store_true", help="keep existing workdir contents")
    ap.add_argument("--skip-network", action="store_true", help="skip CNIPA and mermaid.ink network calls")
    args = ap.parse_args()

    workdir = Path(args.workdir).resolve()
    if workdir.exists() and not args.keep:
        shutil.rmtree(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    paper_dir = write_synthetic_latex(workdir)
    outdir = paper_dir / "patent_disclosure"
    parsed_json = workdir / "paper_parsed.json"
    patents_json = workdir / "patent_results.json"

    run([sys.executable, str(SCRIPT_DIR / "check_env.py"), "--json"], stdout=workdir / "env.json")
    run([sys.executable, str(SCRIPT_DIR / "parse_paper.py"), str(paper_dir), "-o", str(parsed_json)])
    parsed = json.loads(parsed_json.read_text(encoding="utf-8"))

    if args.skip_network:
        patents = []
        patents_json.write_text("[]", encoding="utf-8")
    else:
        run([
            sys.executable,
            str(SCRIPT_DIR / "patent_search.py"),
            "--query",
            "深度学习 图像分割",
            "--max",
            "3",
            "--source",
            "gov",
            "-o",
            str(patents_json),
        ])
        patents = json.loads(patents_json.read_text(encoding="utf-8"))
        real_patents = [p for p in patents if p.get("source") != "no_results"]
        if not real_patents:
            raise AssertionError("CNIPA patent search returned no real patent results")

    md_path = build_disclosure(parsed, patents, outdir)

    if args.skip_network and not shutil.which("mmdc"):
        # Create deterministic placeholder PNGs so offline CI can still test DOCX/image embedding.
        from PIL import Image, ImageDraw
        for i, label in enumerate(["系统架构", "方法流程"], start=1):
            img = Image.new("RGB", (1200, 700), "white")
            d = ImageDraw.Draw(img)
            d.rectangle((40, 40, 1160, 660), outline="black", width=4)
            d.text((80, 80), f"图{i} {label}", fill="black")
            img.save(outdir / f"fig_{i:02d}_{label}.png")
        text = md_path.read_text(encoding="utf-8")
        text = text.replace(text[text.find("```mermaid"):text.find("```", text.find("```mermaid") + 3) + 3], "![图1 系统整体架构](fig_01_系统架构.png)", 1)
        text = text.replace(text[text.find("```mermaid"):text.find("```", text.find("```mermaid") + 3) + 3], "![图2 方法流程](fig_02_方法流程.png)", 1)
        md_path.write_text(text, encoding="utf-8")
    else:
        r = run(["bash", str(SCRIPT_DIR / "mermaid_to_png.sh"), str(md_path), str(outdir)])
        updated = outdir / "_updated.md"
        if updated.is_file():
            md_path.write_text(updated.read_text(encoding="utf-8"), encoding="utf-8")

    docx_path = outdir / "20260602_自适应融合_patent_disclosure.docx"
    run([sys.executable, str(SCRIPT_DIR / "md_to_docx.py"), str(md_path), str(docx_path)])

    assert_outputs(outdir, md_path, docx_path)
    print(json.dumps({
        "status": "ok",
        "workdir": str(workdir),
        "paper_dir": str(paper_dir),
        "output_dir": str(outdir),
        "markdown": str(md_path),
        "docx": str(docx_path),
        "figures": [str(p) for p in sorted(outdir.glob("fig_*.png"))],
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
